### ISSUE TITLE
When will you make your code public?

### ISSUE THREAD

**Issue by BigTree765** [umfieldrobotics/Automatic-Data-Processing-for-Space-Robotics-Machine-Learning#1]
I am particularly interested in exploring the code associated with your work, as it would greatly assist us in our own endeavors. Could you kindly provide information on when you plan to release the code publicly? Knowing the anticipated release date would be immensely helpful for our planning and preparation.

**Comment by anja-sheppard** [comment]
Hi! Thanks for your interest--I'll make it public by the end of the week!

**Comment by anja-sheppard** [comment]
Hi @yusirhhh ! The code has been uploaded. Thanks for your patience! Feel free to open more issues if you have any questions.
